// <auto-generated />
using System;
using AIHR.WorkloadCalculator.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIHR.WorkloadCalculator.Service.Data.Migrations
{
    [DbContext(typeof(WorkloadCalculatorDbContext))]
    partial class WorkloadCalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("AIHR.WorkloadCalculator.Service.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 8,
                            Name = "Blockchain and HR"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 32,
                            Name = "Compensation & Benefits"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 40,
                            Name = "Digital HR"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 10,
                            Name = "Digital HR Strategy"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 8,
                            Name = "Digital HR Transformation"
                        },
                        new
                        {
                            Id = 6,
                            Duration = 20,
                            Name = "Diversity & Inclusion"
                        },
                        new
                        {
                            Id = 7,
                            Duration = 12,
                            Name = "Employee Experience & Design Thinking"
                        },
                        new
                        {
                            Id = 8,
                            Duration = 6,
                            Name = "Employer Branding"
                        },
                        new
                        {
                            Id = 9,
                            Duration = 12,
                            Name = "Global Data Integrity"
                        },
                        new
                        {
                            Id = 10,
                            Duration = 15,
                            Name = "Hiring & Recruitment Strategy"
                        },
                        new
                        {
                            Id = 11,
                            Duration = 21,
                            Name = "HR Analytics Leader"
                        },
                        new
                        {
                            Id = 12,
                            Duration = 40,
                            Name = "HR Business Partner 2.0"
                        },
                        new
                        {
                            Id = 13,
                            Duration = 18,
                            Name = "HR Data Analyst"
                        },
                        new
                        {
                            Id = 14,
                            Duration = 12,
                            Name = "HR Data Science in R"
                        },
                        new
                        {
                            Id = 15,
                            Duration = 12,
                            Name = "HR Data Visualization"
                        },
                        new
                        {
                            Id = 16,
                            Duration = 40,
                            Name = "HR Metrics & Reporting"
                        },
                        new
                        {
                            Id = 17,
                            Duration = 30,
                            Name = "Learning & Development"
                        },
                        new
                        {
                            Id = 18,
                            Duration = 30,
                            Name = "Organizational Development"
                        },
                        new
                        {
                            Id = 19,
                            Duration = 40,
                            Name = "People Analytics"
                        },
                        new
                        {
                            Id = 20,
                            Duration = 15,
                            Name = "Statistics in HR"
                        },
                        new
                        {
                            Id = 21,
                            Duration = 34,
                            Name = "Strategic HR Leadership"
                        },
                        new
                        {
                            Id = 22,
                            Duration = 17,
                            Name = "Strategic HR Metrics"
                        },
                        new
                        {
                            Id = 23,
                            Duration = 40,
                            Name = "Talent Acquisition"
                        });
                });

            modelBuilder.Entity("AIHR.WorkloadCalculator.Service.Models.WorkloadCalculationCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkloadCalculateHistoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkloadCalculateHistoryId");

                    b.ToTable("CalculationHistoryCourses");
                });

            modelBuilder.Entity("AIHR.WorkloadCalculator.Service.WorkloadCalculateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestedDailyStudyHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CalculationHistory");
                });

            modelBuilder.Entity("AIHR.WorkloadCalculator.Service.Models.WorkloadCalculationCourse", b =>
                {
                    b.HasOne("AIHR.WorkloadCalculator.Service.WorkloadCalculateHistory", "WorkloadCalculateHistory")
                        .WithMany("Courses")
                        .HasForeignKey("WorkloadCalculateHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkloadCalculateHistory");
                });

            modelBuilder.Entity("AIHR.WorkloadCalculator.Service.WorkloadCalculateHistory", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
